version: "2"

services:

  builder:
    image: openlmis/dev:5.2
    links:
      - db
      - log
    volumes:
      - '.:/app'
      - '../logback.xml:/logback.xml'
    command: './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    env_file: .env

  image:
    build: .
    image: openlmis/pcmt-integration

  db:
    image: openlmis/postgres:9.6
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/pcmt-integration:/var/log'
